# This workflow will build the Verdict jars, binaries and Docker images

name: Verdict ci-cd build

on:
  push:
    branches: [ ci-cd ]
    tags: [ '*' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        java-version: [ 1.8 ]
        ocaml-version: [ 4.07.1 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GraphViz
      uses: kamiazya/setup-graphviz@v1

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ matrix.os }}-maven-

    - name: Run Maven build
      run: mvn -B install -Dtycho.localArtifacts=ignore --file tools/pom.xml
      env:
        GraphVizPath: /usr/bin

    - name: Set up OCaml
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}

    - name: Cache opam repository
      uses: actions/cache@v2
      with:
        path: ~/.opam
        key: ${{ matrix.os }}-${{ matrix.ocaml-version }}

    - name: Install opam packages
      run: |
        opam install --yes \
          async \
          core \
          core_extended \
          dune \
          menhir \
          ocamlbuild \
          ocamlfind \
          printbox \
          xml-light

    - name: Build aadl2iml
      run: |
        cd tools/verdict-back-ends/aadl2iml
        opam exec make

    - name: Build soteria_pp
      run: |
        cd tools/verdict-back-ends/soteria_pp
        opam exec make

    - name: Build verdict-dev Docker image
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        repository: gehighassurance/verdict-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        tag_with_ref: true
        path: tools/verdict-back-ends
        build_args: BUILDKIT_INLINE_CACHE=1
        cache_froms: gehighassurance/verdict-dev:latest
        push: true

    - name: Build verdict Docker image
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repository: gehighassurance/verdict
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        tag_with_ref: true
        path: tools/verdict-back-ends
        build_args: BUILDKIT_INLINE_CACHE=1
        cache_froms: gehighassurance/verdict:latest
        push: true
